export const menuItems = [
  {
    id: 1,
    title: "Pizza Margarita",
    description: "Pizza clásica con tomate, mozzarella y albahaca fresca.",
    price: 11,
    category: "Pizzas",
    image:
      "https://imgs.search.brave.com/JHkusey2uRc8PIMkvKmEZXsN2Fo6tuNagII3tCZpCGw/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9tZWRp/YS5pc3RvY2twaG90/by5jb20vaWQvMTM5/MjU2OTQ0MC9lcy9m/b3RvL3BpenphLW1h/cmdhcml0YS1zb2Jy/ZS11bi1mb25kby1k/ZS1tYWRlcmEuanBn/P3M9NjEyeDYxMiZ3/PTAmaz0yMCZjPWNV/ZXpTRElfQlhTaFJK/M2VHSS05TkJFcUtv/M3RqTjJjQW8wQ2hx/VWpFX2s9",
    calories: 800,
    fat: 30,
    carbs: 90,
    protein: 25,
    badges: ["Vegetariano", "Clásico"],
  },
  {
    id: 2,
    title: "Pizza Pepperoni",
    description: "Pizza con generosas rodajas de pepperoni y queso fundido.",
    price: 13,
    category: "Pizzas",
    image:
      "https://imgs.search.brave.com/2G5Cmjwm7jLPxMJINRbLhKdD4u_kWfDP3GJ7-1suxik/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9tZWRp/YS5pc3RvY2twaG90/by5jb20vaWQvODA0/MjkxODEwL2VzL2Zv/dG8vcGl6emEtZGUt/cGVwcGVyb25pLXBp/enphLWl0YWxpYW5h/LXNvYnJlLWZvbmRv/LWJsYW5jby5qcGc_/cz02MTJ4NjEyJnc9/MCZrPTIwJmM9M3At/X2Z5QVZKQ1BxdTI3/QThVbkY0dFpYdFQw/alBTclVrRjNoeG1V/U2VIST0",
    calories: 900,
    fat: 40,
    carbs: 85,
    protein: 30,
    badges: ["Picante", "Carnívoro"],
  },
  {
    id: 3,
    title: "Pizza Cuatro Quesos",
    description: "Mozzarella, gorgonzola, parmesano y fontina derretidos.",
    price: 14,
    category: "Pizzas",
    image:
      "https://imgs.search.brave.com/x3Q5lACaPlOKVnK-q4U_3upsSkFJZukJzM580tQooTU/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9tZWRp/YS5pc3RvY2twaG90/by5jb20vaWQvMTQw/NTEwOTUyNC9lcy9m/b3RvL3F1ZXNvcy1k/ZS1waXp6YS1jdWF0/cm8tc29icmUtbGEt/bWVzYS5qcGc_cz02/MTJ4NjEyJnc9MCZr/PTIwJmM9Yi1WMTBw/M3RuSmJ2NWQ5TDVB/UUI0Q1NpTnducEho/NVNMYTg0QUNfRjBI/UT0",
    calories: 950,
    fat: 45,
    carbs: 80,
    protein: 28,
    badges: ["Extra Queso", "Gourmet"],
  },
  {
    id: 4,
    title: "Pizza Vegetariana",
    description: "Cargada de vegetales frescos y queso mozzarella.",
    price: 12,
    category: "Pizzas",
    image:
      "https://imgs.search.brave.com/jrt5FKAy7pqJM6Is7rZZeHutAZXi-7UuuB_7j8g5Pfc/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9tZWRp/YS5pc3RvY2twaG90/by5jb20vaWQvMTg0/OTQ2NzAxL2VzL2Zv/dG8vcGl6emEuanBn/P3M9NjEyeDYxMiZ3/PTAmaz0yMCZjPXhS/djVrbF96SmgzbUZW/ZDR1c2piRDNRblZ6/QUR2T2VSb0RnRUhC/TzJFU2c9",
    calories: 750,
    fat: 25,
    carbs: 85,
    protein: 20,
    badges: ["Vegetariano", "Liviano"],
  },
  {
    id: 5,
    title: "Pizza Fugazzeta",
    description: "Especialidad argentina de pizza rellena de queso y cebolla.",
    price: 15,
    category: "Pizzas",
    image:
      "https://imgs.search.brave.com/3SAOrvVQ-cLEcGDjP6Q8R2zsHMjt3733lDpMmZY9SsE/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9pbWFn/ZW5lcy4yMG1pbnV0/b3MuZXMvZmlsZXMv/aW1hZ2VfOTkwXzU1/Ni91cGxvYWRzL2lt/YWdlbmVzLzIwMjMv/MDQvMDUvZnVnYXp6/ZXRhLmpwZWc",
    calories: 920,
    fat: 38,
    carbs: 88,
    protein: 26,
    badges: ["Típico", "Queso Extra"],
  },
  {
    id: 6,
    title: "Pizza Napolitana",
    description: "Pizza con tomate natural, ajo y orégano.",
    price: 10,
    category: "Pizzas",
    image:
      "https://imgs.search.brave.com/ttOAjDfzjCdnODlaflxVbCPLcsO3-IGcOCQAkNZIfRM/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9tZWRp/YS5pc3RvY2twaG90/by5jb20vaWQvOTE3/NTI3OTY0L2VzL2Zv/dG8vcGl6emEtZGUt/bmFwb2xpLmpwZz9z/PTYxMng2MTImdz0w/Jms9MjAmYz1GUnJz/OUNzeWFtQ0Nta1I4/YmJBUWdINUtRYkJq/cGlNVGkybG5SVUdr/ZTc4PQ",
    calories: 780,
    fat: 28,
    carbs: 82,
    protein: 22,
    badges: ["Clásico", "Sin picante"],
  },
  {
    id: 7,
    title: "Tostadas con Palta",
    description: "Tostadas integrales con palta fresca y semillas.",
    price: 8,
    category: "Desayuno",
    image:
      "https://imgs.search.brave.com/YUNm9_OkVltwkSD-_dz-nS15IBt2r07DNay82FhJgzU/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9pLnBp/bmltZy5jb20vb3Jp/Z2luYWxzL2M5Lzg4/L2U3L2M5ODhlNzli/MTU0NzMzOWNhNDY4/NjZjZmRiN2ZhYTA0/LmpwZw",
    calories: 320,
    fat: 15,
    carbs: 30,
    protein: 10,
    badges: ["Vegano", "Saludable"],
  },
  {
    id: 8,
    title: "Omelette de Verduras",
    description: "Huevos batidos con espinacas, tomate y cebolla.",
    price: 9,
    category: "Desayuno",
    image:
      "https://imgs.search.brave.com/e1hdGpn1M2iaI1AyxFMEggF002rXSUAmUX_TYNkfamA/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9tZWRp/YS5pc3RvY2twaG90/by5jb20vaWQvNDcy/MjA2MzY5L2VzL2Zv/dG8vZGUtb21lbGV0/ZXMuanBnP3M9NjEy/eDYxMiZ3PTAmaz0y/MCZjPXdpbUlLMjli/ckJMX1BFd0NFbmxO/Y1BJOHUyTGthVHpE/dDJnZVlrMVpVQnc9",
    calories: 280,
    fat: 18,
    carbs: 5,
    protein: 18,
    badges: ["Proteico", "Bajo en Carb"],
  },
  {
    id: 9,
    title: "Yogurt con Granola",
    description: "Yogurt natural con granola casera y frutas frescas.",
    price: 7,
    category: "Desayuno",
    image:
      "https://imgs.search.brave.com/QSmaYyCiJjTtyN4Ffk74BrbT5WsQasvTiljPpn3tFUc/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9tZWRp/YS5nZXR0eWltYWdl/cy5jb20vaWQvMTQw/MTg5NTA2Ni9lcy9m/b3RvL2dyYW5vbGEt/Y29uLXlvZ3VydC15/LWZyZXNhcy5qcGc_/cz02MTJ4NjEyJnc9/MCZrPTIwJmM9dGtP/OGN5VGpmOTBUdWdP/ZVhpWllQVDlDbDIx/RzhQaF9yUGZFSVpW/TE5Lcz0",
    calories: 350,
    fat: 10,
    carbs: 45,
    protein: 12,
    badges: ["Fit", "Energético"],
  },
  {
    id: 10,
    title: "Pancakes Americanos",
    description: "Panqueques esponjosos con miel o dulce de leche.",
    price: 9,
    category: "Desayuno",
    image:
      "https://imgs.search.brave.com/9XzgKhncyHETbonZiOkvPZ3FZm2rGrp3ziVhVAY9jZM/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9tZWRp/YS5nZXR0eWltYWdl/cy5jb20vaWQvMTI3/MDEyNDI2OS9lcy9m/b3RvL3BhbnF1ZXF1/ZXMtYW1lcmljYW5v/cy1jb24tZnJ1dGFz/LWVuLWxhLW1lc2Et/ZGUtY2VyY2EuanBn/P3M9NjEyeDYxMiZ3/PTAmaz0yMCZjPUpU/ZndYVi1EaWRBMHll/QmFCcXNxbk5BeFF3/bkZFWWRyVW9HQ3Zq/bUNCYWM9",
    calories: 400,
    fat: 12,
    carbs: 60,
    protein: 8,
    badges: ["Dulce", "Clásico"],
  },
  {
    id: 11,
    title: "Croissant de Manteca",
    description: "Croissant artesanal, dorado y hojaldrado.",
    price: 6,
    category: "Desayuno",
    image:
      "https://imgs.search.brave.com/1Cnuc5tiNzfsds5xuzCxTIpH_IqZVfz0P3pNMDqeTdg/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9pbWct/Z2xvYmFsLmNwY2Ru/LmNvbS9yZWNpcGVz/Lzg5YTg1ZWQ2YWJi/Nzg1OGIvNjgweDk2/NGNxNzAvY3JvaXNz/YW50LWZyYW5jaWEt/Zm90by1wcmluY2lw/YWwuanBn",
    calories: 370,
    fat: 22,
    carbs: 35,
    protein: 6,
    badges: ["Clásico", "Francés"],
  },
  {
    id: 12,
    title: "Huevos Revueltos",
    description: "Huevos revueltos cremosos con cebollín.",
    price: 8,
    category: "Desayuno",
    image:
      "https://imgs.search.brave.com/IYwJjZOFfxcZrydQwk8OiEmp0fxDpaUq1wEErTsfE6A/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly93YWxs/cGFwZXJzLmNvbS9p/bWFnZXMvZmVhdHVy/ZWQvaW1hZ2VuZXMt/ZGUtaHVldm8tcmV2/dWVsdG8tMGV4aG9y/Mm1jMzcxdWVodi5q/cGc",
    calories: 290,
    fat: 20,
    carbs: 2,
    protein: 17,
    badges: ["Proteico", "Salado"],
  },
  {
    id: 13,
    title: "Sándwich de Pollo",
    description: "Pollo grillado en pan integral con lechuga y tomate.",
    price: 10,
    category: "Sandwiches",
    image: "https://images.unsplash.com/photo-1550547660-d9450f859349",
    calories: 480,
    fat: 18,
    carbs: 40,
    protein: 28,
    badges: ["Liviano", "Proteico"],
  },
  {
    id: 29,
    title: "Hamburguesa Simple ",
    description: "Carne grillado en pan integral con lechuga y tomate.",
    price: 10,
    category: "Sandwiches",
    image: "https://images.unsplash.com/photo-1550547660-d9450f859349",
    calories: 480,
    fat: 18,
    carbs: 40,
    protein: 28,
    badges: ["Liviano", "Proteico"],
  },
  {
    id: 14,
    title: "Pastas Caseras",
    description: "Fideos caseros con salsa fileto y albahaca.",
    price: 13,
    category: "Pastas",
    image:
      "https://imgs.search.brave.com/is_2yqiluBPKMV2FA_x2j1wViKOuqeqjmhKfMA3B1AE/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9tZWRp/YS5pc3RvY2twaG90/by5jb20vaWQvOTA4/MTY1MzQ0L2VzL2Zv/dG8vcGFzdGEtY29u/LWNhcm5lLXktdmVy/ZHVyYXMtc29icmUt/Zm9uZG8tYmxhbmNv/LmpwZz9zPTYxMng2/MTImdz0wJms9MjAm/Yz16SU5NT2lRTTBm/U1EtSDNUWjFhRC13/aHFNYnNBWFNmOGdZ/SEdvdGE0Tk1vPQ",
    calories: 620,
    fat: 20,
    carbs: 85,
    protein: 22,
    badges: ["Vegetariano", "Italiano"],
  },
  {
    id: 27,
    title: "Pastas Caseras con Salsa Boloñesa",
    description: "Fideos caseros con salsa Boloñesa.",
    price: 13,
    category: "Pastas",
    image:
      "https://imgs.search.brave.com/is_2yqiluBPKMV2FA_x2j1wViKOuqeqjmhKfMA3B1AE/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9tZWRp/YS5pc3RvY2twaG90/by5jb20vaWQvOTA4/MTY1MzQ0L2VzL2Zv/dG8vcGFzdGEtY29u/LWNhcm5lLXktdmVy/ZHVyYXMtc29icmUt/Zm9uZG8tYmxhbmNv/LmpwZz9zPTYxMng2/MTImdz0wJms9MjAm/Yz16SU5NT2lRTTBm/U1EtSDNUWjFhRC13/aHFNYnNBWFNmOGdZ/SEdvdGE0Tk1vPQ",
    calories: 620,
    fat: 20,
    carbs: 85,
    protein: 22,
    badges: ["Vegetariano", "Italiano"],
  },
  {
    id: 15,
    title: "Wrap Vegetariano",
    description: "Tortilla rellena de vegetales, hummus y quinoa.",
    price: 9,
    category: "Sandwiches",
    image:
      "https://imgs.search.brave.com/ytPBVP4hwP5BNaPYs-X-l0PpjesJbtgSvmKMzf4WMtU/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9nY2Ru/LmVtb2wuY2wvY29j/aW5hL2ZpbGVzLzIw/MTkvMDEvV3JhcHMt/VmVnZXRhcmlhbm9z/LmpwZw",
    calories: 450,
    fat: 16,
    carbs: 50,
    protein: 14,
    badges: ["Vegano", "Ligero"],
  },
  {
    id: 16,
    title: "Ravioles de Ricota",
    description: "Ravioles rellenos de ricota y nuez con salsa rosa.",
    price: 14,
    category: "Pastas",
    image:
      "https://imgs.search.brave.com/sIEN_Z4ypgv1Ni6ssvJRopEghgB7bnw-zbjk3298110/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9tZWRp/YS5hbWJpdG8uY29t/L3AvMWNjYTljY2Y0/ZDBlZmE4YzU4YjU4/MDgxOWRjMjE4ZDUv/YWRqdW50b3MvMjM5/L2ltYWdlbmVzLzA0/MC8yNjcvMDA0MDI2/Nzc1My82MGViZWQ0/ZDRjMTM3OTA2ZDZm/MWE1NzYxZDBkNzM1/Y18zXzNfcGhvdG9q/cGcuanBn",
    calories: 730,
    fat: 26,
    carbs: 90,
    protein: 22,
    badges: ["Clásico", "Italiano"],
  },
  {
    id: 17,
    title: "Risotto de Hongos",
    description: "Arroz cremoso cocido lentamente con hongos frescos.",
    price: 15,
    category: "Platos Elaborados",
    image:
      "https://imgs.search.brave.com/Jlckx6UwXWbTGwz4KglP7-Cztjc5yCXRY5guFmP-lCk/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9tZWRp/YS5nZXR0eWltYWdl/cy5jb20vaWQvODcx/MjQwMDU4L2VzL2Zv/dG8vcmlzb3R0by1o/b25nb3MtcG9yY2lu/aS1lbi1tZXNhLWRl/LW1hZGVyYS1yJUMz/JUJBc3RpY2EuanBn/P3M9NjEyeDYxMiZ3/PTAmaz0yMCZjPVR1/VHhoZ2VWLWRnZ0p1/M185THNuYk4xSzg5/M0hlSU1Ra3BWdVZ0/aC1DajQ9",
    calories: 660,
    fat: 24,
    carbs: 75,
    protein: 18,
    badges: ["Gourmet", "Vegetariano"],
  },
  {
    id: 28,
    title: "Risotto de Hongos con vino",
    description: "Arroz cremoso cocido lentamente con hongos frescos.",
    price: 15,
    category: "Platos Elaborados",
    image:
      "https://imgs.search.brave.com/Jlckx6UwXWbTGwz4KglP7-Cztjc5yCXRY5guFmP-lCk/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9tZWRp/YS5nZXR0eWltYWdl/cy5jb20vaWQvODcx/MjQwMDU4L2VzL2Zv/dG8vcmlzb3R0by1o/b25nb3MtcG9yY2lu/aS1lbi1tZXNhLWRl/LW1hZGVyYS1yJUMz/JUJBc3RpY2EuanBn/P3M9NjEyeDYxMiZ3/PTAmaz0yMCZjPVR1/VHhoZ2VWLWRnZ0p1/M185THNuYk4xSzg5/M0hlSU1Ra3BWdVZ0/aC1DajQ9",
    calories: 660,
    fat: 24,
    carbs: 75,
    protein: 18,
    badges: ["Gourmet", "Vegetariano"],
  },
  {
    id: 18,
    title: "Filet de Merluza",
    description: "Pescado a la plancha con vegetales al vapor.",
    price: 16,
    category: "Platos Elaborados",
    image:
      "https://imgs.search.brave.com/cra_ZBI2NdGBUFBvP6_RfKDcEg8tWjO8w01xDsglA1k/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly93d3cu/Y2xhcmluLmNvbS9p/bWcvMjAyMS8xMS8z/MC9rUHgtbzF0U2pf/NzIweDBfXzEuanBn",
    calories: 490,
    fat: 20,
    carbs: 18,
    protein: 35,
    badges: ["Liviano", "Saludable"],
  },
  {
    id: 19,
    title: "Cheesecake de Frutilla",
    description: "Tarta cremosa de queso con topping de frutillas.",
    price: 8,
    category: "Postres",
    image:
      "https://imgs.search.brave.com/tyaFCUkn9dPtTlhHGo5nFWXK34K6C5DuXyitxdyUrxI/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9ibG9n/Z2VyLmdvb2dsZXVz/ZXJjb250ZW50LmNv/bS9pbWcvYi9SMjl2/WjJ4bC9BVnZYc0Vn/Z1U3UGFkMV9rcVVB/X2pRNTdIMTdwMTdR/U21vdlRFTkg5eUV3/d1hkeDBJMDd1R3Nf/WjRXS1Q4TlNnQXJW/cGFHYXFTdThXOVVN/SkV5WXFoRG11TU9V/X2pfT3Z3TWV2SkRJ/b2VRN2lsUFVmSVp5/emVCLURhckFLS21O/ZkJyVE15bUNTRk9q/NUh2bWp1TFEvczE2/MDAvY2hlZXNlY2th/ZStjb24rZnJ1dGls/bGFzKzIuanBn",
    calories: 420,
    fat: 22,
    carbs: 50,
    protein: 8,
    badges: ["Dulce", "Clásico"],
  },
  {
    id: 20,
    title: "Tiramisú",
    description: "Clásico postre italiano con café, cacao y mascarpone.",
    price: 9,
    category: "Postres",
    image:
      "https://imgs.search.brave.com/M_hDt4ohDoMkKtoAQDwUAKjubiowQSsv_jPAeJ5TudU/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9tZWRp/YS5pc3RvY2twaG90/by5jb20vaWQvMTI4/NzIxMDI2My9lcy9m/b3RvL3RpcmFtaXMl/QzMlQkEtcG9zdHJl/LWl0YWxpYW5vLWNv/bi1zYWJvci1hLWNh/ZiVDMyVBOS5qcGc_/cz02MTJ4NjEyJnc9/MCZrPTIwJmM9TmhK/TENfd2lXdkNNUXdl/eERQU1lYeHhCR25Z/NEZmQ0x3R01VZjBx/b0FfWT0",
    calories: 450,
    fat: 25,
    carbs: 45,
    protein: 7,
    badges: ["Clásico", "Italiano"],
  },
  {
    id: 21,
    title: "Helado Artesanal",
    description: "Helado de crema americana y dulce de leche.",
    price: 6,
    category: "Postres",
    image:
      "https://imgs.search.brave.com/tbtLAoiMx9433imQNoud_Wxp1uByLXWRZFW3aDgjbOo/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9yZXMu/Y2xvdWRpbmFyeS5j/b20vc2hhcmtuaW5q/YS9pbWFnZS91cGxv/YWQvZl9hdXRvLHFf/YXV0by92MTY0NzMz/NDAxMy9TcGFpbi9O/aW5qYS9Db250ZW50/L1BhZ2VzLzAxLiUy/MENyZWFtaSUyMFFS/JTIwQWZ0ZXJzYWxl/cyUyMExhbmRpbmcv/ZWFzeS1udXQtc3By/ZWFkLWljZS1jcmVh/bS1sYW5kc2NhcGUt/MS5qcGc",
    calories: 310,
    fat: 14,
    carbs: 40,
    protein: 6,
    badges: ["Dulce", "Fresco"],
  },
  {
    id: 22,
    title: "Ensalada Caprese",
    description: "Mozzarella, tomate, albahaca y aceite de oliva.",
    price: 9,
    category: "Ensaladas",
    image:
      "https://imgs.search.brave.com/lV_HSSgYNhNPKuOLmSv6M-9WTHUtCwfjVGTSpe7yar4/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9tZWRp/YS5nZXR0eWltYWdl/cy5jb20vaWQvMTMz/NDg1NDE5Mi9lcy9m/b3RvL2Vuc2FsYWRh/LWRlLXBhc3RhLWNh/cHJlc2UuanBnP3M9/NjEyeDYxMiZ3PTAm/az0yMCZjPTMtcjFx/ZkVyTEVENXpyQ2F0/ek5jTWZvZVE0dTJC/dmpUVUhtV1BNX0ln/OVk9",
    calories: 280,
    fat: 18,
    carbs: 10,
    protein: 14,
    badges: ["Liviano", "Italiano"],
  },
  {
    id: 23,
    title: "Ensalada de Quinoa",
    description: "Quinoa con palta, tomate, pepino y limón.",
    price: 10,
    category: "Ensaladas",
    image:
      "https://imgs.search.brave.com/nxpVaFa3RGwgeZFfLZ41ZFzE-KJXulI1_oC7wusrLuA/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9kYW56/YWRlZm9nb25lcy5j/b20vd3AtY29udGVu/dC91cGxvYWRzLzIw/MjQvMDgvZW5zYWxh/ZGEtZGUtcXVpbm9h/LXBhc28tNC5qcGc",
    calories: 320,
    fat: 12,
    carbs: 35,
    protein: 10,
    badges: ["Vegano", "Fit"],
  },
  {
    id: 24,
    title: "Ensalada Thai",
    description: "Zanahoria, repollo, maní y aderezo de sésamo.",
    price: 11,
    category: "Ensaladas",
    image:
      "https://imgs.search.brave.com/TQ9US7rKqvdjU0UFl3VqJAPnpGZcuzBuUTUBNbWPDyc/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9pMC53/cC5jb20vdW5hcGl6/Y2FkZWFtb3IuY29t/L3dwLWNvbnRlbnQv/dXBsb2Fkcy8yMDIx/LzAyL3RoYWktYmVl/Zi1zYWxhZDIuanBn/P3Jlc2l6ZT03NTAs/OTM4JnNzbD0x",
    calories: 310,
    fat: 14,
    carbs: 28,
    protein: 12,
    badges: ["Exótica", "Fresca"],
  },
  {
    id: 25,
    title: "Ensalada César con Pollo",
    description: "Clásica César con pollo grillado.",
    price: 11,
    category: "Ensaladas",
    image:
      "https://imgs.search.brave.com/2eFs4HqRAUzBfG3FCEs_K5SuGWnksn1c0B4BpvG81rQ/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly93d3cu/Y2xhcmluLmNvbS9p/bWcvMjAyMi8xMi8w/MS9MblpGOUV3c2tf/NzIweDBfXzEuanBn",
    calories: 400,
    fat: 20,
    carbs: 20,
    protein: 25,
    badges: ["Proteico", "Clásico"],
  },
  {
    id: 26,
    title: "Ensalada Mediterránea",
    description: "Aceitunas, tomate, queso feta y pepino.",
    price: 10,
    category: "Ensaladas",
    image:
      "https://imgs.search.brave.com/WYnmwZf27GSfL7kc0snZ1sAY3traEdSg8FzLKXsJmJg/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly93YWxs/cGFwZXJzLmNvbS9p/bWFnZXMvZmVhdHVy/ZWQvaW1hZ2VuZXMt/ZGUtZW5zYWxhZGEt/c2dqd3p2cTQwZGg1/aDVwNS5qcGc",
    calories: 300,
    fat: 16,
    carbs: 15,
    protein: 12,
    badges: ["Mediterráneo", "Fresco"],
  },
];

export const categories = [
  "Pizzas",
  "Desayuno",
  "Pastas",
  "Sandwiches",
  "Postres",
  "Platos Elaborados",
  "Ensaladas",
];
